-- TEE v2 异步交付任务（主库：r01_prod）
-- 在应用部署前执行：mysql -uroot -p r01_prod < 2026-08-27-tee-delivery.sql
CREATE TABLE IF NOT EXISTS delivery_secure_jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  transaction_id VARCHAR(128) NOT NULL,
  buyer_address VARCHAR(255) NULL,
  seller_address VARCHAR(255) NULL,
  asset_id VARCHAR(255) NULL,
  vm_cpu INT NOT NULL DEFAULT 8,
  vm_memory_mb INT NOT NULL DEFAULT 4096,
  vm_id VARCHAR(128) NULL,
  vm_status VARCHAR(64) NULL,
  qemu_pid VARCHAR(64) NULL,
  status VARCHAR(64) NOT NULL DEFAULT 'PENDING',
  step VARCHAR(64) NOT NULL DEFAULT 'REQUESTED',
  contract_status VARCHAR(32) NULL,
  data_file_status VARCHAR(32) NULL,
  weight_file_status VARCHAR(32) NULL,
  result_status VARCHAR(32) NULL,
  buyer_key_status VARCHAR(32) NULL,
  data_public_key_pem LONGTEXT NULL,
  data_private_key_pem LONGTEXT NULL,
  weight_public_key_pem LONGTEXT NULL,
  weight_private_key_pem LONGTEXT NULL,
  seller_key_status VARCHAR(32) NULL,
  key1_status VARCHAR(32) NULL,
  key2_status VARCHAR(32) NULL,
  contract_key_envelope LONGTEXT NULL,
  seller_data_key_envelope LONGTEXT NULL,
  buyer_data_key_envelope LONGTEXT NULL,
  contract_verify_result LONGTEXT NULL,
  encrypted_result LONGTEXT NULL,
  last_error TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_delivery_secure_jobs_transaction (transaction_id),
  KEY idx_delivery_secure_jobs_status (status),
  KEY idx_delivery_secure_jobs_vm (vm_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
