CREATE TABLE IF NOT EXISTS fl_delivery_contracts (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  transaction_id VARCHAR(128) NOT NULL,
  business_contract_id VARCHAR(128) NOT NULL,
  pcp_contract_id VARCHAR(128) DEFAULT NULL,
  buyer_id VARCHAR(255) NOT NULL,
  seller_ids_json JSON DEFAULT NULL,
  buyer_result_public_key TEXT DEFAULT NULL,
  max_epochs INT NOT NULL DEFAULT 10,
  learning_rate DOUBLE NOT NULL DEFAULT 0.001,
  batch_size INT NOT NULL DEFAULT 32,
  loss_function VARCHAR(64) NOT NULL DEFAULT 'CrossEntropy',
  dp_noise_scale DOUBLE NOT NULL DEFAULT 0,
  dp_clipping_threshold DOUBLE NOT NULL DEFAULT 1,
  pcp_status VARCHAR(32) DEFAULT 'CREATED',
  current_epoch INT NOT NULL DEFAULT 0,
  buyer_download_token TEXT DEFAULT NULL,
  buyer_result_filename VARCHAR(255) DEFAULT NULL,
  buyer_result_storage_path TEXT DEFAULT NULL,
  seller_join_packages_json JSON DEFAULT NULL,
  seller_result_packages_json JSON DEFAULT NULL,
  last_error TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_fl_tx (transaction_id),
  UNIQUE KEY uniq_fl_pcp_contract (pcp_contract_id),
  KEY idx_fl_business_contract (business_contract_id)
);
