chain_client:
  # 链ID
  chain_id: "chain1"
  # 组织ID
  org_id: "wx-org1.chainmaker.org"
  # 客户端用户私钥路径
  user_key_file_path: "/root/chain1-certs/user/admin1/admin1.tls.key"
  # 客户端用户证书路径
  user_crt_file_path: "/root/chain1-certs/user/admin1/admin1.tls.crt"
  # 客户端用户签名私钥路径
  user_sign_key_file_path: "/root/chain1-certs/user/admin1/admin1.sign.key"
  # 客户端用户签名证书路径
  user_sign_crt_file_path: "/root/chain1-certs/user/admin1/admin1.sign.crt"

  nodes:
    - # Docker 容器访问宿主机 ChainMaker RPC
      node_addr: "host.docker.internal:12301"
      # 节点连接数
      conn_cnt: 10
      # RPC连接是否启用双向TLS认证
      enable_tls: true
      # 信任证书池路径
      trust_root_paths:
        - "/root/chain1-certs/ca/wx-org1.chainmaker.org"
        - "/root/chain1-certs/ca/wx-org2.chainmaker.org"
        - "/root/chain1-certs/ca/wx-org3.chainmaker.org"
        - "/root/chain1-certs/ca/wx-org4.chainmaker.org"
      tls_host_name: "chainmaker.org"
      # 客户端用户TLS私钥路径
      tls_key_file_path: "/root/chain1-certs/user/admin1/admin1.tls.key"
      # 客户端用户TLS证书路径
      tls_cert_file_path: "/root/chain1-certs/user/admin1/admin1.tls.crt"
