// receive-key.c
// Migration-only receive-key service.
//
// Build:
//   gcc -Wall -Wextra -O2 receive-key.c -o receive-key -lssl -lcrypto
//
// Run from this source directory:
//   ./receive-key               # listen on 0.0.0.0:28080
//   ./receive-key 127.0.0.1     # listen locally on port 28080
//
// Runtime files in the current directory:
//   intl.auth        required by hag tkm
//   sm4_enc_key.bin generated by hag tkm app_key_gen
//   sm4_key.bin     extracted 16-byte SM4 key

#define _POSIX_C_SOURCE 200809L

#include <arpa/inet.h>
#include <errno.h>
#include <netinet/in.h>
#include <openssl/bio.h>
#include <openssl/buffer.h>
#include <openssl/evp.h>
#include <openssl/pem.h>
#include <openssl/rand.h>
#include <openssl/sha.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <unistd.h>

#define SM4_KEY_LEN 16
#define SM4_ENC_KEY_PATH "./sm4_enc_key.bin"
#define SM4_KEY_PATH "./sm4_key.bin"

#define INTL_KEY_CMD "hag tkm intl_key_gen -type sm4 -idx 1 -auth intl.auth"
#define APP_KEY_CMD "hag tkm app_key_gen -type sm4 -phandle 0x2000001 -pauth intl.auth -out " SM4_ENC_KEY_PATH

#define GCM_KEY_LEN 32
#define GCM_NONCE_LEN 12
#define GCM_TAG_LEN 16
#define SERVICE_PORT 28080

static const char *g_bind_ip = "0.0.0.0";
static const int g_port = SERVICE_PORT;
static volatile sig_atomic_t g_stopping = 0;
static int g_listen_fd = -1;

static void handle_stop_signal(int signo) {
  (void)signo;
  g_stopping = 1;
  if (g_listen_fd >= 0) {
    close(g_listen_fd);
    g_listen_fd = -1;
  }
}

static int install_signal_handlers(void) {
  struct sigaction stop_action;
  struct sigaction ignore_action;

  memset(&stop_action, 0, sizeof(stop_action));
  stop_action.sa_handler = handle_stop_signal;
  sigemptyset(&stop_action.sa_mask);

  memset(&ignore_action, 0, sizeof(ignore_action));
  ignore_action.sa_handler = SIG_IGN;
  sigemptyset(&ignore_action.sa_mask);

  return sigaction(SIGTERM, &stop_action, NULL) == 0 &&
         sigaction(SIGINT, &stop_action, NULL) == 0 &&
         sigaction(SIGPIPE, &ignore_action, NULL) == 0;
}

static unsigned char *read_file(const char *path, size_t *out_len) {
  FILE *f = fopen(path, "rb");
  if (!f) return NULL;

  if (fseek(f, 0, SEEK_END) != 0) {
    fclose(f);
    return NULL;
  }

  long sz = ftell(f);
  if (sz < 0) {
    fclose(f);
    return NULL;
  }
  rewind(f);

  unsigned char *buf = (unsigned char *)malloc(sz ? (size_t)sz : 1);
  if (!buf) {
    fclose(f);
    return NULL;
  }

  size_t n = fread(buf, 1, (size_t)sz, f);
  fclose(f);
  if (n != (size_t)sz) {
    free(buf);
    return NULL;
  }

  *out_len = n;
  return buf;
}

static int write_file_bin(const char *path, const unsigned char *data, size_t len) {
  FILE *f = fopen(path, "wb");
  if (!f) return 0;

  size_t n = fwrite(data, 1, len, f);
  fclose(f);
  return n == len;
}

static int run_cmd(const char *cmd) {
  int ret = system(cmd);
  if (ret != 0) {
    fprintf(stderr, "Command failed (%d): %s\n", ret, cmd);
    return 0;
  }
  return 1;
}

static int extract_sm4_key_from_enc(const char *enc_path, unsigned char out_key[SM4_KEY_LEN]) {
  size_t n = 0;
  unsigned char *buf = read_file(enc_path, &n);
  if (!buf) {
    perror("read sm4_enc_key.bin failed");
    return 0;
  }

  if (n < 8 + SM4_KEY_LEN) {
    fprintf(stderr, "sm4_enc_key.bin too short: %zu\n", n);
    free(buf);
    return 0;
  }

  memcpy(out_key, buf + 8, SM4_KEY_LEN);
  free(buf);
  return 1;
}

static int generate_extract_save_sm4_key(void) {
  unsigned char key[SM4_KEY_LEN];

  if (!run_cmd(INTL_KEY_CMD)) return 0;
  if (!run_cmd(APP_KEY_CMD)) return 0;
  if (!extract_sm4_key_from_enc(SM4_ENC_KEY_PATH, key)) return 0;
  if (!write_file_bin(SM4_KEY_PATH, key, SM4_KEY_LEN)) {
    fprintf(stderr, "failed to write %s\n", SM4_KEY_PATH);
    return 0;
  }

  return 1;
}

static char *base64_encode(const unsigned char *buf, size_t len) {
  BIO *b64 = BIO_new(BIO_f_base64());
  if (!b64) return NULL;
  BIO_set_flags(b64, BIO_FLAGS_BASE64_NO_NL);

  BIO *bmem = BIO_new(BIO_s_mem());
  if (!bmem) {
    BIO_free_all(b64);
    return NULL;
  }

  b64 = BIO_push(b64, bmem);
  if (BIO_write(b64, buf, (int)len) <= 0 || BIO_flush(b64) != 1) {
    BIO_free_all(b64);
    return NULL;
  }

  BUF_MEM *bptr = NULL;
  BIO_get_mem_ptr(b64, &bptr);
  char *out = (char *)malloc(bptr->length + 1);
  if (!out) {
    BIO_free_all(b64);
    return NULL;
  }

  memcpy(out, bptr->data, bptr->length);
  out[bptr->length] = '\0';
  BIO_free_all(b64);
  return out;
}

static EVP_PKEY *load_pub_from_mem(const char *pem, size_t len) {
  BIO *bio = BIO_new_mem_buf((void *)pem, (int)len);
  if (!bio) return NULL;

  EVP_PKEY *pkey = PEM_read_bio_PUBKEY(bio, NULL, NULL, NULL);
  BIO_free(bio);
  return pkey;
}

static int aes_gcm_encrypt(const unsigned char *key, const unsigned char *nonce,
                           const unsigned char *plain, size_t plen,
                           unsigned char **cipher, size_t *clen,
                           unsigned char tag[GCM_TAG_LEN]) {
  EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
  if (!ctx) return 0;

  int outl = 0;
  int outl2 = 0;
  *cipher = NULL;
  *clen = 0;

  if (EVP_EncryptInit_ex(ctx, EVP_aes_256_gcm(), NULL, NULL, NULL) != 1) goto fail;
  if (EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_SET_IVLEN, GCM_NONCE_LEN, NULL) != 1) goto fail;
  if (EVP_EncryptInit_ex(ctx, NULL, NULL, key, nonce) != 1) goto fail;

  *cipher = (unsigned char *)malloc(plen ? plen : 1);
  if (!*cipher) goto fail;

  if (EVP_EncryptUpdate(ctx, *cipher, &outl, plain, (int)plen) != 1) goto fail;
  if (EVP_EncryptFinal_ex(ctx, *cipher + outl, &outl2) != 1) goto fail;
  if (EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_GET_TAG, GCM_TAG_LEN, tag) != 1) goto fail;

  *clen = (size_t)(outl + outl2);
  EVP_CIPHER_CTX_free(ctx);
  return 1;

fail:
  if (*cipher) {
    free(*cipher);
    *cipher = NULL;
  }
  EVP_CIPHER_CTX_free(ctx);
  return 0;
}

static int kdf_derive_key(const unsigned char *secret, size_t secret_len,
                          const unsigned char *salt, size_t salt_len,
                          const unsigned char *info, size_t info_len,
                          unsigned char out_key[GCM_KEY_LEN]) {
  EVP_MD_CTX *m = EVP_MD_CTX_new();
  if (!m) return 0;

  unsigned char md[SHA256_DIGEST_LENGTH];
  if (EVP_DigestInit_ex(m, EVP_sha256(), NULL) != 1) {
    EVP_MD_CTX_free(m);
    return 0;
  }

  EVP_DigestUpdate(m, secret, secret_len);
  EVP_DigestUpdate(m, salt, salt_len);
  EVP_DigestUpdate(m, info, info_len);

  unsigned int mdlen = 0;
  EVP_DigestFinal_ex(m, md, &mdlen);
  EVP_MD_CTX_free(m);
  memcpy(out_key, md, GCM_KEY_LEN);
  return 1;
}

static int json_get_string(const char *js, long jlen, const char *key,
                           char **out, long *outlen) {
  *out = NULL;
  *outlen = 0;
  size_t klen = strlen(key);

  for (long i = 0; i + (long)klen + 4 < jlen; i++) {
    if (js[i] == '"' && strncmp(js + i + 1, key, klen) == 0 && js[i + 1 + klen] == '"') {
      long p = i + 1 + klen + 1;
      while (p < jlen && js[p] != ':') p++;
      if (p >= jlen) return 0;
      p++;
      while (p < jlen && (js[p] == ' ' || js[p] == '\t')) p++;
      if (p >= jlen || js[p] != '"') return 0;
      p++;

      char *buf = (char *)malloc((size_t)jlen + 1);
      if (!buf) return 0;

      long w = 0;
      while (p < jlen) {
        char c = js[p++];
        if (c == '"') {
          buf[w] = '\0';
          *out = buf;
          *outlen = w;
          return 1;
        }
        if (c == '\\' && p < jlen) {
          char e = js[p++];
          switch (e) {
            case 'n': buf[w++] = '\n'; break;
            case 'r': buf[w++] = '\r'; break;
            case 't': buf[w++] = '\t'; break;
            case '\\': buf[w++] = '\\'; break;
            case '"': buf[w++] = '"'; break;
            default: buf[w++] = e; break;
          }
        } else {
          buf[w++] = c;
        }
      }

      free(buf);
      return 0;
    }
  }

  return 0;
}

static void send_http(int fd, const char *status, const char *headers,
                      const void *body, size_t blen) {
  char head[1024];
  int n = snprintf(head, sizeof(head),
                   "HTTP/1.1 %s\r\n"
                   "%s"
                   "Content-Length: %zu\r\n"
                   "\r\n",
                   status, headers ? headers : "", blen);
  send(fd, head, (size_t)n, 0);
  if (blen) send(fd, body, blen, 0);
}

static void send_json_code_only(int fd, const char *status, int code) {
  char body[128];
  int n = snprintf(body, sizeof(body), "{\"code\":%d}", code);
  if (n < 0) n = 0;
  send_http(fd, status, "Content-Type: application/json\r\nConnection: close\r\n",
            body, (size_t)n);
}

static void send_json_success(int fd, const char *eph_pub, const char *salt,
                              const char *nonce, const char *tag,
                              const char *ciphertext) {
  char body[65536];
  int n = snprintf(body, sizeof(body),
                   "{"
                   "\"code\":200,"
                   "\"ephPub\":\"%s\","
                   "\"salt\":\"%s\","
                   "\"nonce\":\"%s\","
                   "\"tag\":\"%s\","
                   "\"ciphertext\":\"%s\""
                   "}",
                   eph_pub, salt, nonce, tag, ciphertext);
  if (n < 0) n = 0;
  send_http(fd, "200 OK", "Content-Type: application/json\r\nConnection: close\r\n",
            body, (size_t)n);
}

static int parse_request(int fd, char *method, char *path,
                         long *content_length, char **body_out,
                         long *body_len_out) {
  char buf[65536];
  int n = recv(fd, buf, sizeof(buf), MSG_PEEK);
  if (n <= 0) return -1;

  char *hdr_end = NULL;
  for (int i = 0; i < n - 3; i++) {
    if (buf[i] == '\r' && buf[i + 1] == '\n' &&
        buf[i + 2] == '\r' && buf[i + 3] == '\n') {
      hdr_end = buf + i + 4;
      break;
    }
  }
  if (!hdr_end) return -2;

  int header_len = (int)(hdr_end - buf);
  int cr = recv(fd, buf, (size_t)header_len, 0);
  if (cr != header_len) return -3;
  buf[header_len] = '\0';

  char *saveptr = NULL;
  char *line = strtok_r(buf, "\r\n", &saveptr);
  if (!line) return -4;
  sscanf(line, "%15s %1023s", method, path);

  *content_length = -1;
  for (char *p = strtok_r(NULL, "\r\n", &saveptr); p; p = strtok_r(NULL, "\r\n", &saveptr)) {
    if (strncasecmp(p, "Content-Length:", 15) == 0) {
      *content_length = strtol(p + 15, NULL, 10);
    }
  }
  if (*content_length < 0) return -5;

  char *body = (char *)malloc((size_t)*content_length);
  if (!body) return -6;

  long got = 0;
  while (got < *content_length) {
    int r = recv(fd, body + got, (size_t)(*content_length - got), 0);
    if (r <= 0) {
      free(body);
      return -7;
    }
    got += r;
  }

  *body_out = body;
  *body_len_out = *content_length;
  return 0;
}

static void handle_client(int fd) {
  char method[16] = {0};
  char path[1024] = {0};
  long clen = 0;
  char *body = NULL;
  long blen = 0;
  char *pem_buf = NULL;
  long pem_len = 0;

  if (parse_request(fd, method, path, &clen, &body, &blen) != 0) {
    send_json_code_only(fd, "400 Bad Request", 50010);
    goto done;
  }

  (void)clen;

  if (!(strcasecmp(method, "POST") == 0 && strcmp(path, "/api/receive-key") == 0)) {
    send_json_code_only(fd, "404 Not Found", 50011);
    goto done;
  }

  if (!(blen > 0 && body[0] == '{')) {
    send_json_code_only(fd, "400 Bad Request", 50012);
    goto done;
  }

  if (!json_get_string(body, blen, "ecPublicKey", &pem_buf, &pem_len)) {
    send_json_code_only(fd, "400 Bad Request", 50001);
    goto done;
  }

  EVP_PKEY *peer = load_pub_from_mem(pem_buf, (size_t)pem_len);
  if (!peer) {
    send_json_code_only(fd, "400 Bad Request", 50002);
    goto done;
  }
  if (EVP_PKEY_base_id(peer) != EVP_PKEY_EC) {
    EVP_PKEY_free(peer);
    send_json_code_only(fd, "400 Bad Request", 50003);
    goto done;
  }

  if (!generate_extract_save_sm4_key()) {
    EVP_PKEY_free(peer);
    send_json_code_only(fd, "500 Internal Server Error", 50004);
    goto done;
  }

  size_t plen = 0;
  unsigned char *plain = read_file(SM4_KEY_PATH, &plen);
  if (!plain) {
    EVP_PKEY_free(peer);
    send_json_code_only(fd, "500 Internal Server Error", 50005);
    goto done;
  }

  EVP_PKEY *eph = NULL;
  EVP_PKEY_CTX *kctx = EVP_PKEY_CTX_new_id(EVP_PKEY_EC, NULL);
  if (!kctx ||
      EVP_PKEY_keygen_init(kctx) != 1 ||
      EVP_PKEY_CTX_set_ec_paramgen_curve_nid(kctx, NID_X9_62_prime256v1) != 1 ||
      EVP_PKEY_keygen(kctx, &eph) != 1) {
    EVP_PKEY_CTX_free(kctx);
    EVP_PKEY_free(peer);
    free(plain);
    send_json_code_only(fd, "500 Internal Server Error", 50006);
    goto done;
  }
  EVP_PKEY_CTX_free(kctx);

  size_t secret_len = 0;
  EVP_PKEY_CTX *dctx = EVP_PKEY_CTX_new(eph, NULL);
  if (!dctx ||
      EVP_PKEY_derive_init(dctx) != 1 ||
      EVP_PKEY_derive_set_peer(dctx, peer) != 1 ||
      EVP_PKEY_derive(dctx, NULL, &secret_len) != 1) {
    EVP_PKEY_CTX_free(dctx);
    EVP_PKEY_free(eph);
    EVP_PKEY_free(peer);
    free(plain);
    send_json_code_only(fd, "500 Internal Server Error", 50007);
    goto done;
  }

  unsigned char *secret = (unsigned char *)malloc(secret_len);
  if (!secret || EVP_PKEY_derive(dctx, secret, &secret_len) != 1) {
    EVP_PKEY_CTX_free(dctx);
    EVP_PKEY_free(eph);
    EVP_PKEY_free(peer);
    free(secret);
    free(plain);
    send_json_code_only(fd, "500 Internal Server Error", 50007);
    goto done;
  }
  EVP_PKEY_CTX_free(dctx);

  unsigned char salt[16];
  unsigned char nonce[GCM_NONCE_LEN];
  if (RAND_bytes(salt, sizeof(salt)) != 1 || RAND_bytes(nonce, sizeof(nonce)) != 1) {
    OPENSSL_cleanse(secret, secret_len);
    free(secret);
    EVP_PKEY_free(eph);
    EVP_PKEY_free(peer);
    free(plain);
    send_json_code_only(fd, "500 Internal Server Error", 50008);
    goto done;
  }

  unsigned char aes_key[GCM_KEY_LEN];
  const unsigned char info[] = "HENC2-P256-AES256GCM";
  if (!kdf_derive_key(secret, secret_len, salt, sizeof(salt), info, sizeof(info) - 1, aes_key)) {
    OPENSSL_cleanse(secret, secret_len);
    free(secret);
    EVP_PKEY_free(eph);
    EVP_PKEY_free(peer);
    free(plain);
    send_json_code_only(fd, "500 Internal Server Error", 50008);
    goto done;
  }
  OPENSSL_cleanse(secret, secret_len);
  free(secret);

  unsigned char tag[GCM_TAG_LEN];
  unsigned char *ct = NULL;
  size_t ctlen = 0;
  if (!aes_gcm_encrypt(aes_key, nonce, plain, plen, &ct, &ctlen, tag)) {
    EVP_PKEY_free(eph);
    EVP_PKEY_free(peer);
    free(plain);
    send_json_code_only(fd, "500 Internal Server Error", 50008);
    goto done;
  }

  unsigned char *eph_der = NULL;
  int eph_der_len = i2d_PUBKEY(eph, &eph_der);
  EVP_PKEY_free(eph);
  EVP_PKEY_free(peer);
  if (eph_der_len <= 0) {
    free(plain);
    free(ct);
    send_json_code_only(fd, "500 Internal Server Error", 50009);
    goto done;
  }

  char *b64_eph = base64_encode(eph_der, (size_t)eph_der_len);
  char *b64_salt = base64_encode(salt, sizeof(salt));
  char *b64_nonce = base64_encode(nonce, sizeof(nonce));
  char *b64_tag = base64_encode(tag, sizeof(tag));
  char *b64_ct = base64_encode(ct, ctlen);
  if (!b64_eph || !b64_salt || !b64_nonce || !b64_tag || !b64_ct) {
    free(b64_eph);
    free(b64_salt);
    free(b64_nonce);
    free(b64_tag);
    free(b64_ct);
    OPENSSL_free(eph_der);
    free(plain);
    free(ct);
    send_json_code_only(fd, "500 Internal Server Error", 50009);
    goto done;
  }

  send_json_success(fd, b64_eph, b64_salt, b64_nonce, b64_tag, b64_ct);

  free(b64_eph);
  free(b64_salt);
  free(b64_nonce);
  free(b64_tag);
  free(b64_ct);
  OPENSSL_free(eph_der);
  free(plain);
  free(ct);

done:
  free(pem_buf);
  free(body);
  close(fd);
}

int main(int argc, char **argv) {
  if (argc > 2) {
    fprintf(stderr, "Usage: %s [bind_ip]\n", argv[0]);
    fprintf(stderr, "The service port is fixed at %d.\n", SERVICE_PORT);
    return 1;
  }

  if (argc == 2) g_bind_ip = argv[1];

  OpenSSL_add_all_algorithms();
  if (!install_signal_handlers()) {
    perror("sigaction");
    return 2;
  }

  int s = socket(AF_INET, SOCK_STREAM, 0);
  if (s < 0) {
    perror("socket");
    return 2;
  }

  int on = 1;
  setsockopt(s, SOL_SOCKET, SO_REUSEADDR, &on, sizeof(on));

  struct sockaddr_in addr;
  memset(&addr, 0, sizeof(addr));
  addr.sin_family = AF_INET;
  addr.sin_port = htons((uint16_t)g_port);
  if (inet_pton(AF_INET, g_bind_ip, &addr.sin_addr) != 1) {
    fprintf(stderr, "invalid bind ip: %s\n", g_bind_ip);
    close(s);
    return 2;
  }

  if (bind(s, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
    perror("bind");
    close(s);
    return 2;
  }

  if (listen(s, 16) < 0) {
    perror("listen");
    close(s);
    return 3;
  }

  g_listen_fd = s;

  printf("Listening on http://%s:%d (POST /api/receive-key), key=%s\n",
         g_bind_ip, g_port, SM4_KEY_PATH);
  fflush(stdout);

  while (!g_stopping) {
    int c = accept(s, NULL, NULL);
    if (c < 0) {
      if (g_stopping) break;
      if (errno == EINTR) continue;
      perror("accept");
      break;
    }
    handle_client(c);
  }

  if (g_listen_fd >= 0) {
    close(g_listen_fd);
    g_listen_fd = -1;
  }
  fprintf(stderr, "receive-key stopped\n");
  return 0;
}
